FROM python:3.10-slim

WORKDIR /app

# Copier les fichiers nécessaires
COPY app.py /app/
COPY requirements.txt /app/

# Installer uniquement les dépendances de Streamlit
RUN pip install --no-cache-dir -r requirements.txt

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0"]